### ISSUE TITLE
how start

### ISSUE THREAD

**Issue by jalowin** [PetrosKataras/Cinder-NDI#2]
Hello again:

I have a system that producer a NDI content and I can play in Newtek Monitor in windows 7 how can I play this content in your cinder-ndi receiver?

Thanks for all

**Comment by PetrosKataras** [comment]
You just run both your sender and the Cinder-NDI receiver and as long as they are on the same LAN you should see the content also on the receiver side. I am gonna close this since it's not really an issue. For general questions please refer to the forum post so other people can hopefully benefit from the discussions http://discourse.libcinder.org/t/wip-cinder-ndi/322 .
